(setq q1 (cons 1 2))
(setq q2 (cons 2 3))
(setq concat (cons q1 q2))
(setq carres (car concat))
(setq q3 (car carres))
(setq q4 (cdr q2))
(print q1 q2 q3 q4)
(setq numlist (cons 1 2 3 4))
(setq q5 (nthcdr 10 numlist))
(print q5)
(print (nth 1 numlist))